previews:
  generation: automatic

services:
  - type: web
    name: moment-api
    plan: starter
    runtime: node
    region: oregon
    buildCommand: rm -rf ./packages/{app,web,worker,scripts} && pnpm i --ignore-scripts && pnpm build
    preDeployCommand: pnpm -F db migrate:prod
    startCommand: NODE_ENV=production pnpm -F api start
    autoDeploy: true
    envVars:
      - fromGroup: moment
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: moment
          property: connectionString
  
  - type: worker
    name: moment-worker
    plan: starter
    runtime: node
    region: oregon
    buildCommand: rm -rf ./packages/{app,api,web,scripts} && pnpm i --ignore-scripts && pnpm build
    preDeployCommand: pnpm -F db migrate:prod
    startCommand: NODE_ENV=production pnpm -F worker start
    autoDeploy: true
    envVars:
      - fromGroup: moment
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: moment
          property: connectionString

databases:
  - name: moment
    databaseName: moment
    region: oregon
    plan: basic-1gb
    previewPlan: basic-256mb
    postgresMajorVersion: 16

